# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/worldwidehua/battleFatigues

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/worldwidehua/battleFatigues

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/worldwidehua/battleFatigues/CMakeFiles /home/worldwidehua/battleFatigues/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/worldwidehua/battleFatigues/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named battleFatigues

# Build rule for target.
battleFatigues: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 battleFatigues
.PHONY : battleFatigues

# fast build rule for target.
battleFatigues/fast:
	$(MAKE) -f CMakeFiles/battleFatigues.dir/build.make CMakeFiles/battleFatigues.dir/build
.PHONY : battleFatigues/fast

edgeDetector.o: edgeDetector.cpp.o
.PHONY : edgeDetector.o

# target to build an object file
edgeDetector.cpp.o:
	$(MAKE) -f CMakeFiles/battleFatigues.dir/build.make CMakeFiles/battleFatigues.dir/edgeDetector.cpp.o
.PHONY : edgeDetector.cpp.o

edgeDetector.i: edgeDetector.cpp.i
.PHONY : edgeDetector.i

# target to preprocess a source file
edgeDetector.cpp.i:
	$(MAKE) -f CMakeFiles/battleFatigues.dir/build.make CMakeFiles/battleFatigues.dir/edgeDetector.cpp.i
.PHONY : edgeDetector.cpp.i

edgeDetector.s: edgeDetector.cpp.s
.PHONY : edgeDetector.s

# target to generate assembly for a file
edgeDetector.cpp.s:
	$(MAKE) -f CMakeFiles/battleFatigues.dir/build.make CMakeFiles/battleFatigues.dir/edgeDetector.cpp.s
.PHONY : edgeDetector.cpp.s

kMeans.o: kMeans.cpp.o
.PHONY : kMeans.o

# target to build an object file
kMeans.cpp.o:
	$(MAKE) -f CMakeFiles/battleFatigues.dir/build.make CMakeFiles/battleFatigues.dir/kMeans.cpp.o
.PHONY : kMeans.cpp.o

kMeans.i: kMeans.cpp.i
.PHONY : kMeans.i

# target to preprocess a source file
kMeans.cpp.i:
	$(MAKE) -f CMakeFiles/battleFatigues.dir/build.make CMakeFiles/battleFatigues.dir/kMeans.cpp.i
.PHONY : kMeans.cpp.i

kMeans.s: kMeans.cpp.s
.PHONY : kMeans.s

# target to generate assembly for a file
kMeans.cpp.s:
	$(MAKE) -f CMakeFiles/battleFatigues.dir/build.make CMakeFiles/battleFatigues.dir/kMeans.cpp.s
.PHONY : kMeans.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/battleFatigues.dir/build.make CMakeFiles/battleFatigues.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/battleFatigues.dir/build.make CMakeFiles/battleFatigues.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/battleFatigues.dir/build.make CMakeFiles/battleFatigues.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... battleFatigues"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... edgeDetector.o"
	@echo "... edgeDetector.i"
	@echo "... edgeDetector.s"
	@echo "... kMeans.o"
	@echo "... kMeans.i"
	@echo "... kMeans.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

